# Generated by Django 5.0.2 on 2024-07-28 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('step1', '0002_alter_event_manager_alter_venue_email_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='Venue',
            new_name='venue',
        ),
        migrations.AddField(
            model_name='venue',
            name='owner',
            field=models.IntegerField(default=1, verbose_name='Venue Owner'),
        ),
    ]
